#include <sol.hpp>

namespace SolLuaBind 
{
        extern void LuaBind_(lua_State *L);
        extern void LuaBind_Vector2(lua_State *L);
        extern void LuaBind_Axis2(lua_State *L);
        extern void LuaBind_AABB2(lua_State *L);
        extern void LuaBind_OBB2(lua_State *L);
        extern void LuaBind_Circle(lua_State *L);
        extern void LuaBind_Sector(lua_State *L);
        extern void LuaBind_LineSegment(lua_State *L);
        extern void LuaBind_Vector3(lua_State *L);
        extern void LuaBind_MemoryUtil(lua_State *L);
        extern void LuaBind_IAutoReleaseObject(lua_State *L);
        extern void LuaBind_AutoReleaseUtil(lua_State *L);
        extern void LuaBind_Ticker(lua_State *L);
        extern void LuaBind_GeometryUtils(lua_State *L);
        extern void LuaBind_Config(lua_State *L);
        extern void LuaBind_Net(lua_State *L);
        extern void LuaBind_Config(lua_State *L);
        extern void LuaBind_Tuple(lua_State *L);
        extern void LuaBind_Config(lua_State *L);
        extern void LuaBind_Config(lua_State *L);
        extern void LuaBind_Config(lua_State *L);
        extern void LuaBind_Config(lua_State *L);
        extern void LuaBind_Config(lua_State *L);
        extern void LuaBind_Config(lua_State *L);
        extern void LuaBind_NumUtil(lua_State *L);
        extern void LuaBind_Config(lua_State *L);
        extern void LuaBind_Config(lua_State *L);
        extern void LuaBind_Config_CsvLogConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfig(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvConfigSets(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfig(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvConfigSets(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfig(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvConfigSets(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfig(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvConfigSets(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfig(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvConfigSets(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfig(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvConfigSets(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfig(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvConfigSets(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfig(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvConfigSets(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfig(lua_State *L);
        extern void LuaBind_NumUtil_ECalculateStrategy(lua_State *L);
        extern void LuaBind_Config_CsvLogConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfig(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvConfigSets(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfig(lua_State *L);
        extern void LuaBind_Config_CsvLogConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectFilterConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHealConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectGroupConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfig(lua_State *L);
        extern void LuaBind_Config_CsvSceneConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfigSet(lua_State *L);
        extern void LuaBind_Config_CsvConfigSets(lua_State *L);
        extern void LuaBind_Config_CsvEffectAttrsConfig(lua_State *L);
        extern void LuaBind_Config_CsvSkillLevelConfig(lua_State *L);
        extern void LuaBind_Config_CsvEffectHurtConfig(lua_State *L);

	void SolLuaBind(lua_State *L)
	{
            LuaBind_(L);
            LuaBind_Vector2(L);
            LuaBind_Axis2(L);
            LuaBind_AABB2(L);
            LuaBind_OBB2(L);
            LuaBind_Circle(L);
            LuaBind_Sector(L);
            LuaBind_LineSegment(L);
            LuaBind_Vector3(L);
            LuaBind_MemoryUtil(L);
            LuaBind_IAutoReleaseObject(L);
            LuaBind_AutoReleaseUtil(L);
            LuaBind_Ticker(L);
            LuaBind_GeometryUtils(L);
            LuaBind_Config(L);
            LuaBind_Net(L);
            LuaBind_Config(L);
            LuaBind_Tuple(L);
            LuaBind_Config(L);
            LuaBind_Config(L);
            LuaBind_Config(L);
            LuaBind_Config(L);
            LuaBind_Config(L);
            LuaBind_Config(L);
            LuaBind_NumUtil(L);
            LuaBind_Config(L);
            LuaBind_Config(L);
            LuaBind_Config_CsvLogConfig(L);
            LuaBind_Config_CsvLogConfigSet(L);
            LuaBind_Config_CsvSkillConfig(L);
            LuaBind_Config_CsvSkillConfigSet(L);
            LuaBind_Config_CsvEffectFilterConfig(L);
            LuaBind_Config_CsvEffectFilterConfigSet(L);
            LuaBind_Config_CsvEffectHealConfig(L);
            LuaBind_Config_CsvEffectHealConfigSet(L);
            LuaBind_Config_CsvEffectGroupConfig(L);
            LuaBind_Config_CsvEffectGroupConfigSet(L);
            LuaBind_Config_CsvSceneConfig(L);
            LuaBind_Config_CsvSceneConfigSet(L);
            LuaBind_Config_CsvSkillLevelConfigSet(L);
            LuaBind_Config_CsvEffectHurtConfigSet(L);
            LuaBind_Config_CsvEffectAttrsConfigSet(L);
            LuaBind_Config_CsvConfigSets(L);
            LuaBind_Config_CsvEffectAttrsConfig(L);
            LuaBind_Config_CsvSkillLevelConfig(L);
            LuaBind_Config_CsvEffectHurtConfig(L);
            LuaBind_Config_CsvLogConfig(L);
            LuaBind_Config_CsvLogConfigSet(L);
            LuaBind_Config_CsvSkillConfig(L);
            LuaBind_Config_CsvSkillConfigSet(L);
            LuaBind_Config_CsvEffectFilterConfig(L);
            LuaBind_Config_CsvEffectFilterConfigSet(L);
            LuaBind_Config_CsvEffectHealConfig(L);
            LuaBind_Config_CsvEffectHealConfigSet(L);
            LuaBind_Config_CsvEffectGroupConfig(L);
            LuaBind_Config_CsvEffectGroupConfigSet(L);
            LuaBind_Config_CsvSceneConfig(L);
            LuaBind_Config_CsvSceneConfigSet(L);
            LuaBind_Config_CsvSkillLevelConfigSet(L);
            LuaBind_Config_CsvEffectHurtConfigSet(L);
            LuaBind_Config_CsvEffectAttrsConfigSet(L);
            LuaBind_Config_CsvConfigSets(L);
            LuaBind_Config_CsvEffectAttrsConfig(L);
            LuaBind_Config_CsvSkillLevelConfig(L);
            LuaBind_Config_CsvEffectHurtConfig(L);
            LuaBind_Config_CsvLogConfig(L);
            LuaBind_Config_CsvLogConfigSet(L);
            LuaBind_Config_CsvSkillConfig(L);
            LuaBind_Config_CsvSkillConfigSet(L);
            LuaBind_Config_CsvEffectFilterConfig(L);
            LuaBind_Config_CsvEffectFilterConfigSet(L);
            LuaBind_Config_CsvEffectHealConfig(L);
            LuaBind_Config_CsvEffectHealConfigSet(L);
            LuaBind_Config_CsvEffectGroupConfig(L);
            LuaBind_Config_CsvEffectGroupConfigSet(L);
            LuaBind_Config_CsvSceneConfig(L);
            LuaBind_Config_CsvSceneConfigSet(L);
            LuaBind_Config_CsvSkillLevelConfigSet(L);
            LuaBind_Config_CsvEffectHurtConfigSet(L);
            LuaBind_Config_CsvEffectAttrsConfigSet(L);
            LuaBind_Config_CsvConfigSets(L);
            LuaBind_Config_CsvEffectAttrsConfig(L);
            LuaBind_Config_CsvSkillLevelConfig(L);
            LuaBind_Config_CsvEffectHurtConfig(L);
            LuaBind_Config_CsvLogConfig(L);
            LuaBind_Config_CsvLogConfigSet(L);
            LuaBind_Config_CsvSkillConfig(L);
            LuaBind_Config_CsvSkillConfigSet(L);
            LuaBind_Config_CsvEffectFilterConfig(L);
            LuaBind_Config_CsvEffectFilterConfigSet(L);
            LuaBind_Config_CsvEffectHealConfig(L);
            LuaBind_Config_CsvEffectHealConfigSet(L);
            LuaBind_Config_CsvEffectGroupConfig(L);
            LuaBind_Config_CsvEffectGroupConfigSet(L);
            LuaBind_Config_CsvSceneConfig(L);
            LuaBind_Config_CsvSceneConfigSet(L);
            LuaBind_Config_CsvSkillLevelConfigSet(L);
            LuaBind_Config_CsvEffectHurtConfigSet(L);
            LuaBind_Config_CsvEffectAttrsConfigSet(L);
            LuaBind_Config_CsvConfigSets(L);
            LuaBind_Config_CsvEffectAttrsConfig(L);
            LuaBind_Config_CsvSkillLevelConfig(L);
            LuaBind_Config_CsvEffectHurtConfig(L);
            LuaBind_Config_CsvLogConfig(L);
            LuaBind_Config_CsvLogConfigSet(L);
            LuaBind_Config_CsvSkillConfig(L);
            LuaBind_Config_CsvSkillConfigSet(L);
            LuaBind_Config_CsvEffectFilterConfig(L);
            LuaBind_Config_CsvEffectFilterConfigSet(L);
            LuaBind_Config_CsvEffectHealConfig(L);
            LuaBind_Config_CsvEffectHealConfigSet(L);
            LuaBind_Config_CsvEffectGroupConfig(L);
            LuaBind_Config_CsvEffectGroupConfigSet(L);
            LuaBind_Config_CsvSceneConfig(L);
            LuaBind_Config_CsvSceneConfigSet(L);
            LuaBind_Config_CsvSkillLevelConfigSet(L);
            LuaBind_Config_CsvEffectHurtConfigSet(L);
            LuaBind_Config_CsvEffectAttrsConfigSet(L);
            LuaBind_Config_CsvConfigSets(L);
            LuaBind_Config_CsvEffectAttrsConfig(L);
            LuaBind_Config_CsvSkillLevelConfig(L);
            LuaBind_Config_CsvEffectHurtConfig(L);
            LuaBind_Config_CsvLogConfig(L);
            LuaBind_Config_CsvLogConfigSet(L);
            LuaBind_Config_CsvSkillConfig(L);
            LuaBind_Config_CsvSkillConfigSet(L);
            LuaBind_Config_CsvEffectFilterConfig(L);
            LuaBind_Config_CsvEffectFilterConfigSet(L);
            LuaBind_Config_CsvEffectHealConfig(L);
            LuaBind_Config_CsvEffectHealConfigSet(L);
            LuaBind_Config_CsvEffectGroupConfig(L);
            LuaBind_Config_CsvEffectGroupConfigSet(L);
            LuaBind_Config_CsvSceneConfig(L);
            LuaBind_Config_CsvSceneConfigSet(L);
            LuaBind_Config_CsvSkillLevelConfigSet(L);
            LuaBind_Config_CsvEffectHurtConfigSet(L);
            LuaBind_Config_CsvEffectAttrsConfigSet(L);
            LuaBind_Config_CsvConfigSets(L);
            LuaBind_Config_CsvEffectAttrsConfig(L);
            LuaBind_Config_CsvSkillLevelConfig(L);
            LuaBind_Config_CsvEffectHurtConfig(L);
            LuaBind_Config_CsvLogConfig(L);
            LuaBind_Config_CsvLogConfigSet(L);
            LuaBind_Config_CsvSkillConfig(L);
            LuaBind_Config_CsvSkillConfigSet(L);
            LuaBind_Config_CsvEffectFilterConfig(L);
            LuaBind_Config_CsvEffectFilterConfigSet(L);
            LuaBind_Config_CsvEffectHealConfig(L);
            LuaBind_Config_CsvEffectHealConfigSet(L);
            LuaBind_Config_CsvEffectGroupConfig(L);
            LuaBind_Config_CsvEffectGroupConfigSet(L);
            LuaBind_Config_CsvSceneConfig(L);
            LuaBind_Config_CsvSceneConfigSet(L);
            LuaBind_Config_CsvSkillLevelConfigSet(L);
            LuaBind_Config_CsvEffectHurtConfigSet(L);
            LuaBind_Config_CsvEffectAttrsConfigSet(L);
            LuaBind_Config_CsvConfigSets(L);
            LuaBind_Config_CsvEffectAttrsConfig(L);
            LuaBind_Config_CsvSkillLevelConfig(L);
            LuaBind_Config_CsvEffectHurtConfig(L);
            LuaBind_Config_CsvLogConfig(L);
            LuaBind_Config_CsvLogConfigSet(L);
            LuaBind_Config_CsvSkillConfig(L);
            LuaBind_Config_CsvSkillConfigSet(L);
            LuaBind_Config_CsvEffectFilterConfig(L);
            LuaBind_Config_CsvEffectFilterConfigSet(L);
            LuaBind_Config_CsvEffectHealConfig(L);
            LuaBind_Config_CsvEffectHealConfigSet(L);
            LuaBind_Config_CsvEffectGroupConfig(L);
            LuaBind_Config_CsvEffectGroupConfigSet(L);
            LuaBind_Config_CsvSceneConfig(L);
            LuaBind_Config_CsvSceneConfigSet(L);
            LuaBind_Config_CsvSkillLevelConfigSet(L);
            LuaBind_Config_CsvEffectHurtConfigSet(L);
            LuaBind_Config_CsvEffectAttrsConfigSet(L);
            LuaBind_Config_CsvConfigSets(L);
            LuaBind_Config_CsvEffectAttrsConfig(L);
            LuaBind_Config_CsvSkillLevelConfig(L);
            LuaBind_Config_CsvEffectHurtConfig(L);
            LuaBind_NumUtil_ECalculateStrategy(L);
            LuaBind_Config_CsvLogConfig(L);
            LuaBind_Config_CsvLogConfigSet(L);
            LuaBind_Config_CsvSkillConfig(L);
            LuaBind_Config_CsvSkillConfigSet(L);
            LuaBind_Config_CsvEffectFilterConfig(L);
            LuaBind_Config_CsvEffectFilterConfigSet(L);
            LuaBind_Config_CsvEffectHealConfig(L);
            LuaBind_Config_CsvEffectHealConfigSet(L);
            LuaBind_Config_CsvEffectGroupConfig(L);
            LuaBind_Config_CsvEffectGroupConfigSet(L);
            LuaBind_Config_CsvSceneConfig(L);
            LuaBind_Config_CsvSceneConfigSet(L);
            LuaBind_Config_CsvSkillLevelConfigSet(L);
            LuaBind_Config_CsvEffectHurtConfigSet(L);
            LuaBind_Config_CsvEffectAttrsConfigSet(L);
            LuaBind_Config_CsvConfigSets(L);
            LuaBind_Config_CsvEffectAttrsConfig(L);
            LuaBind_Config_CsvSkillLevelConfig(L);
            LuaBind_Config_CsvEffectHurtConfig(L);
            LuaBind_Config_CsvLogConfig(L);
            LuaBind_Config_CsvLogConfigSet(L);
            LuaBind_Config_CsvSkillConfig(L);
            LuaBind_Config_CsvSkillConfigSet(L);
            LuaBind_Config_CsvEffectFilterConfig(L);
            LuaBind_Config_CsvEffectFilterConfigSet(L);
            LuaBind_Config_CsvEffectHealConfig(L);
            LuaBind_Config_CsvEffectHealConfigSet(L);
            LuaBind_Config_CsvEffectGroupConfig(L);
            LuaBind_Config_CsvEffectGroupConfigSet(L);
            LuaBind_Config_CsvSceneConfig(L);
            LuaBind_Config_CsvSceneConfigSet(L);
            LuaBind_Config_CsvSkillLevelConfigSet(L);
            LuaBind_Config_CsvEffectHurtConfigSet(L);
            LuaBind_Config_CsvEffectAttrsConfigSet(L);
            LuaBind_Config_CsvConfigSets(L);
            LuaBind_Config_CsvEffectAttrsConfig(L);
            LuaBind_Config_CsvSkillLevelConfig(L);
            LuaBind_Config_CsvEffectHurtConfig(L);
	}
}