// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BattleEnum.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NetProto {

  /// <summary>Holder for reflection information generated from BattleEnum.proto</summary>
  public static partial class BattleEnumReflection {

    #region Descriptor
    /// <summary>File descriptor for BattleEnum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BattleEnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBCYXR0bGVFbnVtLnByb3RvEghOZXRQcm90byo4CgxFU2NlbmVPYmplY3QS",
            "DAoIQnVpbGRpbmcQABIICgRIZXJvEAESBwoDTnBjEAISBwoDTUFYEAMq4AEK",
            "D0VNb3ZlQWdlbnRTdGF0ZRIYChRFTW92ZUFnZW50U3RhdGVfSWRsZRAAEh0K",
            "GUVNb3ZlQWdlbnRTdGF0ZV9Nb3ZlVG9Qb3MQARIdChlFTW92ZUFnZW50U3Rh",
            "dGVfTW92ZVRvRGlyEAISHwobRU1vdmVBZ2VudFN0YXRlX0ltbW9iaWxpemVk",
            "EAMSHQoZRU1vdmVBZ2VudFN0YXRlX0ZvcmNlTGluZRAEEhwKGEVNb3ZlQWdl",
            "bnRTdGF0ZV9Gb3JjZVBvcxAFEhcKE0VNb3ZlQWdlbnRTdGF0ZV9NYXgQBips",
            "CgpFTW92ZVN0YXRlEhMKD0VNb3ZlU3RhdGVfSWRsZRAAEhMKD0VNb3ZlU3Rh",
            "dGVfTW92ZRABEhoKFkVNb3ZlU3RhdGVfSW1tb2JpbGl6ZWQQAhIYChRFTW92",
            "ZVN0YXRlX0ZvcmNlTW92ZRADQgP4AQFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NetProto.ESceneObject), typeof(global::NetProto.EMoveAgentState), typeof(global::NetProto.EMoveState), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ESceneObject {
    [pbr::OriginalName("Building")] Building = 0,
    [pbr::OriginalName("Hero")] Hero = 1,
    [pbr::OriginalName("Npc")] Npc = 2,
    [pbr::OriginalName("MAX")] Max = 3,
  }

  public enum EMoveAgentState {
    [pbr::OriginalName("EMoveAgentState_Idle")] Idle = 0,
    [pbr::OriginalName("EMoveAgentState_MoveToPos")] MoveToPos = 1,
    [pbr::OriginalName("EMoveAgentState_MoveToDir")] MoveToDir = 2,
    [pbr::OriginalName("EMoveAgentState_Immobilized")] Immobilized = 3,
    [pbr::OriginalName("EMoveAgentState_ForceLine")] ForceLine = 4,
    [pbr::OriginalName("EMoveAgentState_ForcePos")] ForcePos = 5,
    [pbr::OriginalName("EMoveAgentState_Max")] Max = 6,
  }

  public enum EMoveState {
    [pbr::OriginalName("EMoveState_Idle")] Idle = 0,
    [pbr::OriginalName("EMoveState_Move")] Move = 1,
    [pbr::OriginalName("EMoveState_Immobilized")] Immobilized = 2,
    [pbr::OriginalName("EMoveState_ForceMove")] ForceMove = 3,
  }

  #endregion

}

#endregion Designer generated code
