// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Battle.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NetProto {

  /// <summary>Holder for reflection information generated from Battle.proto</summary>
  public static partial class BattleReflection {

    #region Descriptor
    /// <summary>File descriptor for Battle.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BattleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxCYXR0bGUucHJvdG8SCE5ldFByb3RvGgxDb21tb24ucHJvdG8aEEJhdHRs",
            "ZUVudW0ucHJvdG8iOAoLUnNwRnJlZUhlcm8SEwoLcmVkX2hlcm9faWQYASAB",
            "KAQSFAoMYmx1ZV9oZXJvX2lkGAIgASgEIiAKDVNlbGVjdEhlcm9SZXESDwoH",
            "aGVyb19pZBgBIAEoBCIxCg1TZWxlY3RIZXJvUnNwEg8KB2hlcm9faWQYASAB",
            "KAQSDwoHaXNfc3VjYxgCIAEoCCKRAQoQU2NlbmVPYmplY3RTdGF0ZRINCgVv",
            "YmppZBgBIAEoBBIoCghvYmpfdHlwZRgCIAEoDjIWLk5ldFByb3RvLkVTY2Vu",
            "ZU9iamVjdBIQCghtb2RlbF9pZBgDIAEoBRIgCgNwb3MYBCABKAsyEy5OZXRQ",
            "cm90by5QQlZlY3RvcjMSEAoIcm90YXRpb24YBSABKAIigQEKD01vdmVPYmpl",
            "Y3RTdGF0ZRItCglvYmpfc3RhdGUYASABKAsyGi5OZXRQcm90by5TY2VuZU9i",
            "amVjdFN0YXRlEg4KBnJhZGl1cxgCIAEoBRIOCgZoZWlnaHQYAyABKAUSDAoE",
            "bWFzcxgEIAEoBRIRCgltYXhfc3BlZWQYBSABKAUitwEKFk1vdmVPYmplY3RN",
            "dXRhYmxlU3RhdGUSDQoFb2JqaWQYASABKAQSMwoQbW92ZV9hZ2VudF9zdGF0",
            "ZRgCIAEoDjIZLk5ldFByb3RvLkVNb3ZlQWdlbnRTdGF0ZRIlCgh2b2xlY2l0",
            "eRgDIAEoCzITLk5ldFByb3RvLlBCVmVjdG9yMxIgCgNwb3MYBCABKAsyEy5O",
            "ZXRQcm90by5QQlZlY3RvcjMSEAoIcm90YXRpb24YBSABKAIiLQoJTW92ZVRv",
            "UG9zEiAKA3BvcxgBIAEoCzITLk5ldFByb3RvLlBCVmVjdG9yMkID+AEBYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::NetProto.CommonReflection.Descriptor, global::NetProto.BattleEnumReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NetProto.RspFreeHero), global::NetProto.RspFreeHero.Parser, new[]{ "RedHeroId", "BlueHeroId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NetProto.SelectHeroReq), global::NetProto.SelectHeroReq.Parser, new[]{ "HeroId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NetProto.SelectHeroRsp), global::NetProto.SelectHeroRsp.Parser, new[]{ "HeroId", "IsSucc" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NetProto.SceneObjectState), global::NetProto.SceneObjectState.Parser, new[]{ "Objid", "ObjType", "ModelId", "Pos", "Rotation" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NetProto.MoveObjectState), global::NetProto.MoveObjectState.Parser, new[]{ "ObjState", "Radius", "Height", "Mass", "MaxSpeed" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NetProto.MoveObjectMutableState), global::NetProto.MoveObjectMutableState.Parser, new[]{ "Objid", "MoveAgentState", "Volecity", "Pos", "Rotation" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NetProto.MoveToPos), global::NetProto.MoveToPos.Parser, new[]{ "Pos" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RspFreeHero : pb::IMessage<RspFreeHero> {
    private static readonly pb::MessageParser<RspFreeHero> _parser = new pb::MessageParser<RspFreeHero>(() => new RspFreeHero());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RspFreeHero> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NetProto.BattleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RspFreeHero() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RspFreeHero(RspFreeHero other) : this() {
      redHeroId_ = other.redHeroId_;
      blueHeroId_ = other.blueHeroId_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RspFreeHero Clone() {
      return new RspFreeHero(this);
    }

    /// <summary>Field number for the "red_hero_id" field.</summary>
    public const int RedHeroIdFieldNumber = 1;
    private ulong redHeroId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong RedHeroId {
      get { return redHeroId_; }
      set {
        redHeroId_ = value;
      }
    }

    /// <summary>Field number for the "blue_hero_id" field.</summary>
    public const int BlueHeroIdFieldNumber = 2;
    private ulong blueHeroId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong BlueHeroId {
      get { return blueHeroId_; }
      set {
        blueHeroId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RspFreeHero);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RspFreeHero other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RedHeroId != other.RedHeroId) return false;
      if (BlueHeroId != other.BlueHeroId) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RedHeroId != 0UL) hash ^= RedHeroId.GetHashCode();
      if (BlueHeroId != 0UL) hash ^= BlueHeroId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RedHeroId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(RedHeroId);
      }
      if (BlueHeroId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(BlueHeroId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RedHeroId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RedHeroId);
      }
      if (BlueHeroId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(BlueHeroId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RspFreeHero other) {
      if (other == null) {
        return;
      }
      if (other.RedHeroId != 0UL) {
        RedHeroId = other.RedHeroId;
      }
      if (other.BlueHeroId != 0UL) {
        BlueHeroId = other.BlueHeroId;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            RedHeroId = input.ReadUInt64();
            break;
          }
          case 16: {
            BlueHeroId = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SelectHeroReq : pb::IMessage<SelectHeroReq> {
    private static readonly pb::MessageParser<SelectHeroReq> _parser = new pb::MessageParser<SelectHeroReq>(() => new SelectHeroReq());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SelectHeroReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NetProto.BattleReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SelectHeroReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SelectHeroReq(SelectHeroReq other) : this() {
      heroId_ = other.heroId_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SelectHeroReq Clone() {
      return new SelectHeroReq(this);
    }

    /// <summary>Field number for the "hero_id" field.</summary>
    public const int HeroIdFieldNumber = 1;
    private ulong heroId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong HeroId {
      get { return heroId_; }
      set {
        heroId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SelectHeroReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SelectHeroReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HeroId != other.HeroId) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HeroId != 0UL) hash ^= HeroId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HeroId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(HeroId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HeroId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(HeroId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SelectHeroReq other) {
      if (other == null) {
        return;
      }
      if (other.HeroId != 0UL) {
        HeroId = other.HeroId;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            HeroId = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SelectHeroRsp : pb::IMessage<SelectHeroRsp> {
    private static readonly pb::MessageParser<SelectHeroRsp> _parser = new pb::MessageParser<SelectHeroRsp>(() => new SelectHeroRsp());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SelectHeroRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NetProto.BattleReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SelectHeroRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SelectHeroRsp(SelectHeroRsp other) : this() {
      heroId_ = other.heroId_;
      isSucc_ = other.isSucc_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SelectHeroRsp Clone() {
      return new SelectHeroRsp(this);
    }

    /// <summary>Field number for the "hero_id" field.</summary>
    public const int HeroIdFieldNumber = 1;
    private ulong heroId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong HeroId {
      get { return heroId_; }
      set {
        heroId_ = value;
      }
    }

    /// <summary>Field number for the "is_succ" field.</summary>
    public const int IsSuccFieldNumber = 2;
    private bool isSucc_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsSucc {
      get { return isSucc_; }
      set {
        isSucc_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SelectHeroRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SelectHeroRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HeroId != other.HeroId) return false;
      if (IsSucc != other.IsSucc) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HeroId != 0UL) hash ^= HeroId.GetHashCode();
      if (IsSucc != false) hash ^= IsSucc.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HeroId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(HeroId);
      }
      if (IsSucc != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsSucc);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HeroId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(HeroId);
      }
      if (IsSucc != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SelectHeroRsp other) {
      if (other == null) {
        return;
      }
      if (other.HeroId != 0UL) {
        HeroId = other.HeroId;
      }
      if (other.IsSucc != false) {
        IsSucc = other.IsSucc;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            HeroId = input.ReadUInt64();
            break;
          }
          case 16: {
            IsSucc = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SceneObjectState : pb::IMessage<SceneObjectState> {
    private static readonly pb::MessageParser<SceneObjectState> _parser = new pb::MessageParser<SceneObjectState>(() => new SceneObjectState());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SceneObjectState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NetProto.BattleReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SceneObjectState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SceneObjectState(SceneObjectState other) : this() {
      objid_ = other.objid_;
      objType_ = other.objType_;
      modelId_ = other.modelId_;
      Pos = other.pos_ != null ? other.Pos.Clone() : null;
      rotation_ = other.rotation_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SceneObjectState Clone() {
      return new SceneObjectState(this);
    }

    /// <summary>Field number for the "objid" field.</summary>
    public const int ObjidFieldNumber = 1;
    private ulong objid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Objid {
      get { return objid_; }
      set {
        objid_ = value;
      }
    }

    /// <summary>Field number for the "obj_type" field.</summary>
    public const int ObjTypeFieldNumber = 2;
    private global::NetProto.ESceneObject objType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NetProto.ESceneObject ObjType {
      get { return objType_; }
      set {
        objType_ = value;
      }
    }

    /// <summary>Field number for the "model_id" field.</summary>
    public const int ModelIdFieldNumber = 3;
    private int modelId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ModelId {
      get { return modelId_; }
      set {
        modelId_ = value;
      }
    }

    /// <summary>Field number for the "pos" field.</summary>
    public const int PosFieldNumber = 4;
    private global::NetProto.PBVector3 pos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NetProto.PBVector3 Pos {
      get { return pos_; }
      set {
        pos_ = value;
      }
    }

    /// <summary>Field number for the "rotation" field.</summary>
    public const int RotationFieldNumber = 5;
    private float rotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Rotation {
      get { return rotation_; }
      set {
        rotation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SceneObjectState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SceneObjectState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Objid != other.Objid) return false;
      if (ObjType != other.ObjType) return false;
      if (ModelId != other.ModelId) return false;
      if (!object.Equals(Pos, other.Pos)) return false;
      if (Rotation != other.Rotation) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Objid != 0UL) hash ^= Objid.GetHashCode();
      if (ObjType != 0) hash ^= ObjType.GetHashCode();
      if (ModelId != 0) hash ^= ModelId.GetHashCode();
      if (pos_ != null) hash ^= Pos.GetHashCode();
      if (Rotation != 0F) hash ^= Rotation.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Objid != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Objid);
      }
      if (ObjType != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ObjType);
      }
      if (ModelId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ModelId);
      }
      if (pos_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Pos);
      }
      if (Rotation != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Rotation);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Objid != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Objid);
      }
      if (ObjType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ObjType);
      }
      if (ModelId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ModelId);
      }
      if (pos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos);
      }
      if (Rotation != 0F) {
        size += 1 + 4;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SceneObjectState other) {
      if (other == null) {
        return;
      }
      if (other.Objid != 0UL) {
        Objid = other.Objid;
      }
      if (other.ObjType != 0) {
        ObjType = other.ObjType;
      }
      if (other.ModelId != 0) {
        ModelId = other.ModelId;
      }
      if (other.pos_ != null) {
        if (pos_ == null) {
          pos_ = new global::NetProto.PBVector3();
        }
        Pos.MergeFrom(other.Pos);
      }
      if (other.Rotation != 0F) {
        Rotation = other.Rotation;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Objid = input.ReadUInt64();
            break;
          }
          case 16: {
            objType_ = (global::NetProto.ESceneObject) input.ReadEnum();
            break;
          }
          case 24: {
            ModelId = input.ReadInt32();
            break;
          }
          case 34: {
            if (pos_ == null) {
              pos_ = new global::NetProto.PBVector3();
            }
            input.ReadMessage(pos_);
            break;
          }
          case 45: {
            Rotation = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  public sealed partial class MoveObjectState : pb::IMessage<MoveObjectState> {
    private static readonly pb::MessageParser<MoveObjectState> _parser = new pb::MessageParser<MoveObjectState>(() => new MoveObjectState());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MoveObjectState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NetProto.BattleReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MoveObjectState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MoveObjectState(MoveObjectState other) : this() {
      ObjState = other.objState_ != null ? other.ObjState.Clone() : null;
      radius_ = other.radius_;
      height_ = other.height_;
      mass_ = other.mass_;
      maxSpeed_ = other.maxSpeed_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MoveObjectState Clone() {
      return new MoveObjectState(this);
    }

    /// <summary>Field number for the "obj_state" field.</summary>
    public const int ObjStateFieldNumber = 1;
    private global::NetProto.SceneObjectState objState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NetProto.SceneObjectState ObjState {
      get { return objState_; }
      set {
        objState_ = value;
      }
    }

    /// <summary>Field number for the "radius" field.</summary>
    public const int RadiusFieldNumber = 2;
    private int radius_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Radius {
      get { return radius_; }
      set {
        radius_ = value;
      }
    }

    /// <summary>Field number for the "height" field.</summary>
    public const int HeightFieldNumber = 3;
    private int height_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Height {
      get { return height_; }
      set {
        height_ = value;
      }
    }

    /// <summary>Field number for the "mass" field.</summary>
    public const int MassFieldNumber = 4;
    private int mass_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Mass {
      get { return mass_; }
      set {
        mass_ = value;
      }
    }

    /// <summary>Field number for the "max_speed" field.</summary>
    public const int MaxSpeedFieldNumber = 5;
    private int maxSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MaxSpeed {
      get { return maxSpeed_; }
      set {
        maxSpeed_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MoveObjectState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MoveObjectState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ObjState, other.ObjState)) return false;
      if (Radius != other.Radius) return false;
      if (Height != other.Height) return false;
      if (Mass != other.Mass) return false;
      if (MaxSpeed != other.MaxSpeed) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (objState_ != null) hash ^= ObjState.GetHashCode();
      if (Radius != 0) hash ^= Radius.GetHashCode();
      if (Height != 0) hash ^= Height.GetHashCode();
      if (Mass != 0) hash ^= Mass.GetHashCode();
      if (MaxSpeed != 0) hash ^= MaxSpeed.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (objState_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ObjState);
      }
      if (Radius != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Radius);
      }
      if (Height != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Height);
      }
      if (Mass != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Mass);
      }
      if (MaxSpeed != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(MaxSpeed);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (objState_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ObjState);
      }
      if (Radius != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Radius);
      }
      if (Height != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Height);
      }
      if (Mass != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Mass);
      }
      if (MaxSpeed != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxSpeed);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MoveObjectState other) {
      if (other == null) {
        return;
      }
      if (other.objState_ != null) {
        if (objState_ == null) {
          objState_ = new global::NetProto.SceneObjectState();
        }
        ObjState.MergeFrom(other.ObjState);
      }
      if (other.Radius != 0) {
        Radius = other.Radius;
      }
      if (other.Height != 0) {
        Height = other.Height;
      }
      if (other.Mass != 0) {
        Mass = other.Mass;
      }
      if (other.MaxSpeed != 0) {
        MaxSpeed = other.MaxSpeed;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (objState_ == null) {
              objState_ = new global::NetProto.SceneObjectState();
            }
            input.ReadMessage(objState_);
            break;
          }
          case 16: {
            Radius = input.ReadInt32();
            break;
          }
          case 24: {
            Height = input.ReadInt32();
            break;
          }
          case 32: {
            Mass = input.ReadInt32();
            break;
          }
          case 40: {
            MaxSpeed = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class MoveObjectMutableState : pb::IMessage<MoveObjectMutableState> {
    private static readonly pb::MessageParser<MoveObjectMutableState> _parser = new pb::MessageParser<MoveObjectMutableState>(() => new MoveObjectMutableState());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MoveObjectMutableState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NetProto.BattleReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MoveObjectMutableState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MoveObjectMutableState(MoveObjectMutableState other) : this() {
      objid_ = other.objid_;
      moveAgentState_ = other.moveAgentState_;
      Volecity = other.volecity_ != null ? other.Volecity.Clone() : null;
      Pos = other.pos_ != null ? other.Pos.Clone() : null;
      rotation_ = other.rotation_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MoveObjectMutableState Clone() {
      return new MoveObjectMutableState(this);
    }

    /// <summary>Field number for the "objid" field.</summary>
    public const int ObjidFieldNumber = 1;
    private ulong objid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Objid {
      get { return objid_; }
      set {
        objid_ = value;
      }
    }

    /// <summary>Field number for the "move_agent_state" field.</summary>
    public const int MoveAgentStateFieldNumber = 2;
    private global::NetProto.EMoveAgentState moveAgentState_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NetProto.EMoveAgentState MoveAgentState {
      get { return moveAgentState_; }
      set {
        moveAgentState_ = value;
      }
    }

    /// <summary>Field number for the "volecity" field.</summary>
    public const int VolecityFieldNumber = 3;
    private global::NetProto.PBVector3 volecity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NetProto.PBVector3 Volecity {
      get { return volecity_; }
      set {
        volecity_ = value;
      }
    }

    /// <summary>Field number for the "pos" field.</summary>
    public const int PosFieldNumber = 4;
    private global::NetProto.PBVector3 pos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NetProto.PBVector3 Pos {
      get { return pos_; }
      set {
        pos_ = value;
      }
    }

    /// <summary>Field number for the "rotation" field.</summary>
    public const int RotationFieldNumber = 5;
    private float rotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Rotation {
      get { return rotation_; }
      set {
        rotation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MoveObjectMutableState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MoveObjectMutableState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Objid != other.Objid) return false;
      if (MoveAgentState != other.MoveAgentState) return false;
      if (!object.Equals(Volecity, other.Volecity)) return false;
      if (!object.Equals(Pos, other.Pos)) return false;
      if (Rotation != other.Rotation) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Objid != 0UL) hash ^= Objid.GetHashCode();
      if (MoveAgentState != 0) hash ^= MoveAgentState.GetHashCode();
      if (volecity_ != null) hash ^= Volecity.GetHashCode();
      if (pos_ != null) hash ^= Pos.GetHashCode();
      if (Rotation != 0F) hash ^= Rotation.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Objid != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Objid);
      }
      if (MoveAgentState != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) MoveAgentState);
      }
      if (volecity_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Volecity);
      }
      if (pos_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Pos);
      }
      if (Rotation != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Rotation);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Objid != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Objid);
      }
      if (MoveAgentState != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MoveAgentState);
      }
      if (volecity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Volecity);
      }
      if (pos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos);
      }
      if (Rotation != 0F) {
        size += 1 + 4;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MoveObjectMutableState other) {
      if (other == null) {
        return;
      }
      if (other.Objid != 0UL) {
        Objid = other.Objid;
      }
      if (other.MoveAgentState != 0) {
        MoveAgentState = other.MoveAgentState;
      }
      if (other.volecity_ != null) {
        if (volecity_ == null) {
          volecity_ = new global::NetProto.PBVector3();
        }
        Volecity.MergeFrom(other.Volecity);
      }
      if (other.pos_ != null) {
        if (pos_ == null) {
          pos_ = new global::NetProto.PBVector3();
        }
        Pos.MergeFrom(other.Pos);
      }
      if (other.Rotation != 0F) {
        Rotation = other.Rotation;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Objid = input.ReadUInt64();
            break;
          }
          case 16: {
            moveAgentState_ = (global::NetProto.EMoveAgentState) input.ReadEnum();
            break;
          }
          case 26: {
            if (volecity_ == null) {
              volecity_ = new global::NetProto.PBVector3();
            }
            input.ReadMessage(volecity_);
            break;
          }
          case 34: {
            if (pos_ == null) {
              pos_ = new global::NetProto.PBVector3();
            }
            input.ReadMessage(pos_);
            break;
          }
          case 45: {
            Rotation = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  public sealed partial class MoveToPos : pb::IMessage<MoveToPos> {
    private static readonly pb::MessageParser<MoveToPos> _parser = new pb::MessageParser<MoveToPos>(() => new MoveToPos());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MoveToPos> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NetProto.BattleReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MoveToPos() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MoveToPos(MoveToPos other) : this() {
      Pos = other.pos_ != null ? other.Pos.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MoveToPos Clone() {
      return new MoveToPos(this);
    }

    /// <summary>Field number for the "pos" field.</summary>
    public const int PosFieldNumber = 1;
    private global::NetProto.PBVector2 pos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NetProto.PBVector2 Pos {
      get { return pos_; }
      set {
        pos_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MoveToPos);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MoveToPos other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Pos, other.Pos)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (pos_ != null) hash ^= Pos.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (pos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Pos);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (pos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MoveToPos other) {
      if (other == null) {
        return;
      }
      if (other.pos_ != null) {
        if (pos_ == null) {
          pos_ = new global::NetProto.PBVector2();
        }
        Pos.MergeFrom(other.Pos);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (pos_ == null) {
              pos_ = new global::NetProto.PBVector2();
            }
            input.ReadMessage(pos_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
