// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoId.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NetProto {

  /// <summary>Holder for reflection information generated from ProtoId.proto</summary>
  public static partial class ProtoIdReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtoId.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1Qcm90b0lkLnByb3RvEghOZXRQcm90byr5AwoHUHJvdG9JZBILCgdQSURf",
            "TWluEAASDAoIUElEX1BpbmcQARIMCghQSURfUG9uZxACEhUKEVBJRF9RdWVy",
            "eUZyZWVIZXJvEGQSEwoPUElEX1JzcEZyZWVIZXJvEGUSFQoRUElEX1NlbGVj",
            "dEhlcm9SZXEQZhIVChFQSURfU2VsZWN0SGVyb1JzcBBnEhkKFVBJRF9Mb2Fk",
            "U2NlbmVDb21wbGV0ZRBoEhIKDlBJRF9MZWF2ZVNjZW5lEGkSHQoYUElEX1Nj",
            "ZW5lT2JqZWN0RGlzYXBwZWFyEPIHEhIKDVBJRF9Nb3ZlVG9Qb3MQ/AcSEQoM",
            "UElEX1N0b3BNb3ZlEIYIEhcKElBJRF9CYXR0bGVPcGVyYVJlcRDMCBIVChBQ",
            "SURfVmlld1NuYXBzaG90ENYIEhUKEFBJRF9WaWV3QWxsR3JpZHMQ1wgSGQoU",
            "UElEX1ZpZXdTbmFwc2hvdERpZmYQ2AgSFwoSUElEX1NjZW5lVW5pdFN0YXRl",
            "ELAJEhsKFlBJRF9TY2VuZVVuaXRUcmFuc2Zvcm0QsQkSFgoRUElEX1NjZW5l",
            "VW5pdE1vdmUQsgkSHQoYUElEX1NjZW5lVW5pdFNraWxsQWN0aW9uELMJEhkK",
            "FFBJRF9SZWxvYWRMdWFTY3JpcHRzEKEfEgwKB1BJRF9NYXgQgChCA/gBAWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NetProto.ProtoId), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ProtoId {
    [pbr::OriginalName("PID_Min")] PidMin = 0,
    [pbr::OriginalName("PID_Ping")] PidPing = 1,
    [pbr::OriginalName("PID_Pong")] PidPong = 2,
    [pbr::OriginalName("PID_QueryFreeHero")] PidQueryFreeHero = 100,
    [pbr::OriginalName("PID_RspFreeHero")] PidRspFreeHero = 101,
    [pbr::OriginalName("PID_SelectHeroReq")] PidSelectHeroReq = 102,
    [pbr::OriginalName("PID_SelectHeroRsp")] PidSelectHeroRsp = 103,
    [pbr::OriginalName("PID_LoadSceneComplete")] PidLoadSceneComplete = 104,
    [pbr::OriginalName("PID_LeaveScene")] PidLeaveScene = 105,
    [pbr::OriginalName("PID_SceneObjectDisappear")] PidSceneObjectDisappear = 1010,
    [pbr::OriginalName("PID_MoveToPos")] PidMoveToPos = 1020,
    [pbr::OriginalName("PID_StopMove")] PidStopMove = 1030,
    [pbr::OriginalName("PID_BattleOperaReq")] PidBattleOperaReq = 1100,
    [pbr::OriginalName("PID_ViewSnapshot")] PidViewSnapshot = 1110,
    [pbr::OriginalName("PID_ViewAllGrids")] PidViewAllGrids = 1111,
    [pbr::OriginalName("PID_ViewSnapshotDiff")] PidViewSnapshotDiff = 1112,
    [pbr::OriginalName("PID_SceneUnitState")] PidSceneUnitState = 1200,
    [pbr::OriginalName("PID_SceneUnitTransform")] PidSceneUnitTransform = 1201,
    [pbr::OriginalName("PID_SceneUnitMove")] PidSceneUnitMove = 1202,
    [pbr::OriginalName("PID_SceneUnitSkillAction")] PidSceneUnitSkillAction = 1203,
    [pbr::OriginalName("PID_ReloadLuaScripts")] PidReloadLuaScripts = 4001,
    [pbr::OriginalName("PID_Max")] PidMax = 5120,
  }

  #endregion

}

#endregion Designer generated code
