// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoId.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ProtoId.proto</summary>
public static partial class ProtoIdReflection {

  #region Descriptor
  /// <summary>File descriptor for ProtoId.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ProtoIdReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1Qcm90b0lkLnByb3RvKpoBCgdQcm90b0lkEgsKB1BJRF9NaW4QABIMCghQ",
          "SURfUGluZxABEgwKCFBJRF9Qb25nEAISFQoRUElEX1F1ZXJ5RnJlZUhlcm8Q",
          "ZBITCg9QSURfUnNwRnJlZUhlcm8QZRIVChFQSURfU2VsZWN0SGVyb1JlcRBm",
          "EhUKEVBJRF9TZWxlY3RIZXJvUnNwEGcSDAoHUElEX01heBCAKEID+AEBYgZw",
          "cm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ProtoId), }, null));
  }
  #endregion

}
#region Enums
public enum ProtoId {
  [pbr::OriginalName("PID_Min")] PidMin = 0,
  [pbr::OriginalName("PID_Ping")] PidPing = 1,
  [pbr::OriginalName("PID_Pong")] PidPong = 2,
  [pbr::OriginalName("PID_QueryFreeHero")] PidQueryFreeHero = 100,
  [pbr::OriginalName("PID_RspFreeHero")] PidRspFreeHero = 101,
  [pbr::OriginalName("PID_SelectHeroReq")] PidSelectHeroReq = 102,
  [pbr::OriginalName("PID_SelectHeroRsp")] PidSelectHeroRsp = 103,
  [pbr::OriginalName("PID_Max")] PidMax = 5120,
}

#endregion


#endregion Designer generated code
