# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BattleEnum.proto',
  package='NetProto',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x42\x61ttleEnum.proto\x12\x08NetProto*8\n\x0c\x45SceneObject\x12\x0c\n\x08\x42uilding\x10\x00\x12\x08\n\x04Hero\x10\x01\x12\x07\n\x03Npc\x10\x02\x12\x07\n\x03MAX\x10\x03*\xe0\x01\n\x0f\x45MoveAgentState\x12\x18\n\x14\x45MoveAgentState_Idle\x10\x00\x12\x1d\n\x19\x45MoveAgentState_MoveToPos\x10\x01\x12\x1d\n\x19\x45MoveAgentState_MoveToDir\x10\x02\x12\x1f\n\x1b\x45MoveAgentState_Immobilized\x10\x03\x12\x1d\n\x19\x45MoveAgentState_ForceLine\x10\x04\x12\x1c\n\x18\x45MoveAgentState_ForcePos\x10\x05\x12\x17\n\x13\x45MoveAgentState_Max\x10\x06*l\n\nEMoveState\x12\x13\n\x0f\x45MoveState_Idle\x10\x00\x12\x13\n\x0f\x45MoveState_Move\x10\x01\x12\x1a\n\x16\x45MoveState_Immobilized\x10\x02\x12\x18\n\x14\x45MoveState_ForceMove\x10\x03\x42\x03\xf8\x01\x01\x62\x06proto3')
)

_ESCENEOBJECT = _descriptor.EnumDescriptor(
  name='ESceneObject',
  full_name='NetProto.ESceneObject',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Building', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Hero', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Npc', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAX', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=30,
  serialized_end=86,
)
_sym_db.RegisterEnumDescriptor(_ESCENEOBJECT)

ESceneObject = enum_type_wrapper.EnumTypeWrapper(_ESCENEOBJECT)
_EMOVEAGENTSTATE = _descriptor.EnumDescriptor(
  name='EMoveAgentState',
  full_name='NetProto.EMoveAgentState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EMoveAgentState_Idle', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMoveAgentState_MoveToPos', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMoveAgentState_MoveToDir', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMoveAgentState_Immobilized', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMoveAgentState_ForceLine', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMoveAgentState_ForcePos', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMoveAgentState_Max', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=89,
  serialized_end=313,
)
_sym_db.RegisterEnumDescriptor(_EMOVEAGENTSTATE)

EMoveAgentState = enum_type_wrapper.EnumTypeWrapper(_EMOVEAGENTSTATE)
_EMOVESTATE = _descriptor.EnumDescriptor(
  name='EMoveState',
  full_name='NetProto.EMoveState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EMoveState_Idle', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMoveState_Move', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMoveState_Immobilized', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMoveState_ForceMove', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=315,
  serialized_end=423,
)
_sym_db.RegisterEnumDescriptor(_EMOVESTATE)

EMoveState = enum_type_wrapper.EnumTypeWrapper(_EMOVESTATE)
Building = 0
Hero = 1
Npc = 2
MAX = 3
EMoveAgentState_Idle = 0
EMoveAgentState_MoveToPos = 1
EMoveAgentState_MoveToDir = 2
EMoveAgentState_Immobilized = 3
EMoveAgentState_ForceLine = 4
EMoveAgentState_ForcePos = 5
EMoveAgentState_Max = 6
EMoveState_Idle = 0
EMoveState_Move = 1
EMoveState_Immobilized = 2
EMoveState_ForceMove = 3


DESCRIPTOR.enum_types_by_name['ESceneObject'] = _ESCENEOBJECT
DESCRIPTOR.enum_types_by_name['EMoveAgentState'] = _EMOVEAGENTSTATE
DESCRIPTOR.enum_types_by_name['EMoveState'] = _EMOVESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\370\001\001'))
# @@protoc_insertion_point(module_scope)
