# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Common.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x43ommon.proto\"\x0c\n\nTestCommonB\x03\xf8\x01\x01\x62\x06proto3')
)




_TESTCOMMON = _descriptor.Descriptor(
  name='TestCommon',
  full_name='TestCommon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=28,
)

DESCRIPTOR.message_types_by_name['TestCommon'] = _TESTCOMMON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestCommon = _reflection.GeneratedProtocolMessageType('TestCommon', (_message.Message,), dict(
  DESCRIPTOR = _TESTCOMMON,
  __module__ = 'Common_pb2'
  # @@protoc_insertion_point(class_scope:TestCommon)
  ))
_sym_db.RegisterMessage(TestCommon)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\370\001\001'))
# @@protoc_insertion_point(module_scope)
