// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Instruction.proto

#ifndef PROTOBUF_Instruction_2eproto_INCLUDED
#define PROTOBUF_Instruction_2eproto_INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_Instruction_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsReloadLuaScriptsImpl();
void InitDefaultsReloadLuaScripts();
inline void InitDefaults() {
  InitDefaultsReloadLuaScripts();
}
}  // namespace protobuf_Instruction_2eproto
namespace NetProto {
class ReloadLuaScripts;
class ReloadLuaScriptsDefaultTypeInternal;
extern ReloadLuaScriptsDefaultTypeInternal _ReloadLuaScripts_default_instance_;
}  // namespace NetProto
namespace google {
namespace protobuf {
template<> ::NetProto::ReloadLuaScripts* Arena::CreateMessage< ::NetProto::ReloadLuaScripts>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace NetProto {

// ===================================================================

class ReloadLuaScripts : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NetProto.ReloadLuaScripts) */ {
 public:
  ReloadLuaScripts();
  virtual ~ReloadLuaScripts();

  ReloadLuaScripts(const ReloadLuaScripts& from);

  inline ReloadLuaScripts& operator=(const ReloadLuaScripts& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReloadLuaScripts(ReloadLuaScripts&& from) noexcept
    : ReloadLuaScripts() {
    *this = ::std::move(from);
  }

  inline ReloadLuaScripts& operator=(ReloadLuaScripts&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const PROTOBUF_FINAL {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const PROTOBUF_FINAL {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReloadLuaScripts& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReloadLuaScripts* internal_default_instance() {
    return reinterpret_cast<const ReloadLuaScripts*>(
               &_ReloadLuaScripts_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void UnsafeArenaSwap(ReloadLuaScripts* other);
  void Swap(ReloadLuaScripts* other);
  friend void swap(ReloadLuaScripts& a, ReloadLuaScripts& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReloadLuaScripts* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::CreateMessage<ReloadLuaScripts>(NULL);
  }

  ReloadLuaScripts* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::CreateMessage<ReloadLuaScripts>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ReloadLuaScripts& from);
  void MergeFrom(const ReloadLuaScripts& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ReloadLuaScripts* other);
  protected:
  explicit ReloadLuaScripts(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string scripts = 1;
  int scripts_size() const;
  void clear_scripts();
  static const int kScriptsFieldNumber = 1;
  const ::std::string& scripts(int index) const;
  ::std::string* mutable_scripts(int index);
  void set_scripts(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_scripts(int index, ::std::string&& value);
  #endif
  void set_scripts(int index, const char* value);
  void set_scripts(int index, const char* value, size_t size);
  ::std::string* add_scripts();
  void add_scripts(const ::std::string& value);
  #if LANG_CXX11
  void add_scripts(::std::string&& value);
  #endif
  void add_scripts(const char* value);
  void add_scripts(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& scripts() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_scripts();

  // @@protoc_insertion_point(class_scope:NetProto.ReloadLuaScripts)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::RepeatedPtrField< ::std::string> scripts_;
  mutable int _cached_size_;
  friend struct ::protobuf_Instruction_2eproto::TableStruct;
  friend void ::protobuf_Instruction_2eproto::InitDefaultsReloadLuaScriptsImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReloadLuaScripts

// repeated string scripts = 1;
inline int ReloadLuaScripts::scripts_size() const {
  return scripts_.size();
}
inline void ReloadLuaScripts::clear_scripts() {
  scripts_.Clear();
}
inline const ::std::string& ReloadLuaScripts::scripts(int index) const {
  // @@protoc_insertion_point(field_get:NetProto.ReloadLuaScripts.scripts)
  return scripts_.Get(index);
}
inline ::std::string* ReloadLuaScripts::mutable_scripts(int index) {
  // @@protoc_insertion_point(field_mutable:NetProto.ReloadLuaScripts.scripts)
  return scripts_.Mutable(index);
}
inline void ReloadLuaScripts::set_scripts(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:NetProto.ReloadLuaScripts.scripts)
  scripts_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void ReloadLuaScripts::set_scripts(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:NetProto.ReloadLuaScripts.scripts)
  scripts_.Mutable(index)->assign(std::move(value));
}
#endif
inline void ReloadLuaScripts::set_scripts(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  scripts_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:NetProto.ReloadLuaScripts.scripts)
}
inline void ReloadLuaScripts::set_scripts(int index, const char* value, size_t size) {
  scripts_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:NetProto.ReloadLuaScripts.scripts)
}
inline ::std::string* ReloadLuaScripts::add_scripts() {
  // @@protoc_insertion_point(field_add_mutable:NetProto.ReloadLuaScripts.scripts)
  return scripts_.Add();
}
inline void ReloadLuaScripts::add_scripts(const ::std::string& value) {
  scripts_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:NetProto.ReloadLuaScripts.scripts)
}
#if LANG_CXX11
inline void ReloadLuaScripts::add_scripts(::std::string&& value) {
  scripts_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:NetProto.ReloadLuaScripts.scripts)
}
#endif
inline void ReloadLuaScripts::add_scripts(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  scripts_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:NetProto.ReloadLuaScripts.scripts)
}
inline void ReloadLuaScripts::add_scripts(const char* value, size_t size) {
  scripts_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:NetProto.ReloadLuaScripts.scripts)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ReloadLuaScripts::scripts() const {
  // @@protoc_insertion_point(field_list:NetProto.ReloadLuaScripts.scripts)
  return scripts_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ReloadLuaScripts::mutable_scripts() {
  // @@protoc_insertion_point(field_mutable_list:NetProto.ReloadLuaScripts.scripts)
  return &scripts_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace NetProto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Instruction_2eproto_INCLUDED
