// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_AISCENEUNITHERO_H_
#define _BEHAVIAC_AISCENEUNITHERO_H_

#include "behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

namespace GameLogic
{
	class SceneHeroAction;
	class SceneUnit;
	class SceneUnitSkills;
}

///<<< END WRITING YOUR CODE

class AISceneUnitHero : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE AISceneUnitHero
///<<< END WRITING YOUR CODE
{
public:
	AISceneUnitHero();
	virtual ~AISceneUnitHero();

	BEHAVIAC_DECLARE_AGENTTYPE(AISceneUnitHero, behaviac::Agent)

	public: long long hero;

	public: unsigned long skill_keyid;

	public: void Init(long long param);

	public: void PickSkill();

	public: void CaskSkill();

///<<< BEGIN WRITING YOUR CODE CLASS_PART

			void ResetData();
			GameLogic::SceneHeroAction *m_su_action = nullptr;
			GameLogic::SceneUnit *m_su = nullptr;
			GameLogic::SceneUnitSkills *m_skills = nullptr;

///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
